spring.application.name=sistema-inventario-backend
server.port=8080

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/inventario
spring.data.mongodb.auto-index-creation=true

# JWT Configuration
jwt.secret=bXlTdXBlclNlY3JldEtleUZvckludmVudGFyaW9TeXN0ZW0yMDI1TXVzdEJlQXRMZWFzdDI1NkJpdHM=
jwt.expiration=86400000

# CORS
app.cors.allowed-origins=http://localhost:4200
